apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  PRODUCT_DATABASE_URL: REPLACE_WITH_RDS_PRODUCT_DATABASE_URL
  ORDER_DATABASE_URL: REPLACE_WITH_RDS_ORDER_DATABASE_URL
  API_TOKEN: REPLACE_WITH_API_TOKEN