name: Infra CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform checks
        run: |
          terraform -chdir=terraform fmt -check
          terraform -chdir=terraform init
          terraform -chdir=terraform validate
          terraform -chdir=terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform -chdir=terraform apply -auto-approve tfplan